# Generated by Django 4.1.5 on 2023-01-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_myfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfiles',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
